const books = [
  {
    id: 1,
    title: "The Hobbit",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    authors: [{ firstName: "J.R.R.", lastName: "Tolkien", id: 1 }],
    price: 290,
    rating: 4.8,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1937-09-21"),
  },
  {
    id: 2,
    title: "1984",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    authors: [{ firstName: "George", lastName: "Orwell", id: 2 }],
    price: 190,
    rating: 4.7,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1949-06-08"),
  },
  {
    id: 3,
    title: "Pride and Prejudice",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141040349-L.jpg",
    authors: [{ firstName: "Jane", lastName: "Austen", id: 3 }],
    price: 145,
    rating: 4.6,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1813-01-28"),
  },
  {
    id: 4,
    title: "The Great Gatsby",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    authors: [{ firstName: "F. Scott", lastName: "Fitzgerald", id: 4 }],
    price: 24,
    rating: 4.4,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1925-04-10"),
  },
  {
    id: 5,
    title: "To Kill a Mockingbird",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    authors: [{ firstName: "Harper", lastName: "Lee", id: 5 }],
    price: 22,
    rating: 4.9,
    isAudio: true,
    isInfinity: true,
    createdAt: new Date("1960-07-11"),
  },
  {
    id: 6,
    title: "The Catcher in the Rye",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
    authors: [{ firstName: "J.D.", lastName: "Salinger", id: 6 }],
    price: 18,
    rating: 4.3,
    isAudio: false,
    isInfinity: false,
    createdAt: new Date("1951-07-16"),
  },
  {
    id: 7,
    title: "Moby-Dick",
    coverUri: "https://covers.openlibrary.org/b/isbn/9781503280786-L.jpg",
    authors: [{ firstName: "Herman", lastName: "Melville", id: 7 }],
    price: 20,
    rating: 4.2,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1851-10-18"),
  },
  {
    id: 8,
    title: "War and Peace",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780199232765-L.jpg",
    authors: [{ firstName: "Leo", lastName: "Tolstoy", id: 8 }],
    price: 35,
    rating: 4.8,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1869-01-01"),
  },
  {
    id: 9,
    title: "The Alchemist",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
    authors: [{ firstName: "Paulo", lastName: "Coelho", id: 9 }],
    price: 15,
    rating: 4.7,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1988-01-01"),
  },
  {
    id: 10,
    title: "Brave New World",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
    authors: [{ firstName: "Aldous", lastName: "Huxley", id: 10 }],
    price: 219,
    rating: 4.5,
    isAudio: false,
    isInfinity: false,
    createdAt: new Date("1932-01-01"),
  },
  {
    id: 11,
    title: "Crime and Punishment",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780486415871-L.jpg",
    authors: [{ firstName: "Fyodor", lastName: "Dostoevsky", id: 11 }],
    price: 28,
    rating: 4.7,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1866-01-01"),
  },
  {
    id: 12,
    title: "The Brothers Karamazov",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780374528379-L.jpg",
    authors: [{ firstName: "Fyodor", lastName: "Dostoevsky", id: 11 }],
    price: 32,
    rating: 4.9,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1880-01-01"),
  },
  {
    id: 13,
    title: "Anna Karenina",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780143035008-L.jpg",
    authors: [{ firstName: "Leo", lastName: "Tolstoy", id: 8 }],
    price: 27,
    rating: 4.6,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1877-01-01"),
  },
  {
    id: 14,
    title: "Don Quixote",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780060934347-L.jpg",
    authors: [{ firstName: "Miguel", lastName: "de Cervantes", id: 14 }],
    price: 30,
    rating: 4.8,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1605-01-01"),
  },
  {
    id: 15,
    title: "Frankenstein",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780486282114-L.jpg",
    authors: [{ firstName: "Mary", lastName: "Shelley", id: 15 }],
    price: 459,
    rating: 4.4,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1818-01-01"),
  },
  {
    id: 16,
    title: "The Odyssey",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780140268867-L.jpg",
    authors: [{ firstName: "Homer", lastName: "", id: 16 }],
    price: 25,
    rating: 4.7,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("-800-01-01"),
  },
  {
    id: 17,
    title: "Dracula",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780393970128-L.jpg",
    authors: [{ firstName: "Bram", lastName: "Stoker", id: 17 }],
    price: 20,
    rating: 4.5,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1897-05-26"),
  },
  {
    id: 18,
    title: "Jane Eyre",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg",
    authors: [{ firstName: "Charlotte", lastName: "Brontë", id: 18 }],
    price: 23,
    rating: 4.6,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1847-10-16"),
  },
  {
    id: 19,
    title: "The Divine Comedy",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780142437223-L.jpg",
    authors: [{ firstName: "Dante", lastName: "Alighieri", id: 19 }],
    price: 99.9,
    rating: 4.9,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1320-01-01"),
  },
  {
    id: 20,
    title: "Les Misérables",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780140444308-L.jpg",
    authors: [{ firstName: "Victor", lastName: "Hugo", id: 20 }],
    price: 35,
    rating: 4.8,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1862-01-01"),
  },
  {
    id: 21,
    title: "Moby-Dick",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780142437247-L.jpg",
    authors: [{ firstName: "Herman", lastName: "Melville", id: 21 }],
    price: 28,
    rating: 4.5,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1851-10-18"),
  },
  {
    id: 22,
    title: "Wuthering Heights",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg",
    authors: [{ firstName: "Emily", lastName: "Brontë", id: 22 }],
    price: 22,
    rating: 4.4,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1847-12-01"),
  },
  {
    id: 23,
    title: "The Picture of Dorian Gray",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141439570-L.jpg",
    authors: [{ firstName: "Oscar", lastName: "Wilde", id: 23 }],
    price: 18,
    rating: 4.3,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1890-06-01"),
  },
  {
    id: 24,
    title: "The Brothers Grimm Fairy Tales",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780451530772-L.jpg",
    authors: [
      { firstName: "Jacob", lastName: "Grimm", id: 24 },
      { firstName: "Wilhelm", lastName: "Grimm", id: 25 },
    ],
    price: 15,
    rating: 4.7,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1812-12-01"),
  },
  {
    id: 25,
    title: "The Catcher in the Rye",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
    authors: [{ firstName: "J.D.", lastName: "Salinger", id: 26 }],
    price: 700,
    rating: 4.1,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1951-07-16"),
  },
  {
    id: 26,
    title: "Pride and Prejudice",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    authors: [{ firstName: "Jane", lastName: "Austen", id: 27 }],
    price: 22,
    rating: 4.6,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1813-01-28"),
  },
  {
    id: 27,
    title: "The Hobbit",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780345339683-L.jpg",
    authors: [{ firstName: "J.R.R.", lastName: "Tolkien", id: 28 }],
    price: 24,
    rating: 4.8,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1937-09-21"),
  },
  {
    id: 28,
    title: "Ulysses",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141182803-L.jpg",
    authors: [{ firstName: "James", lastName: "Joyce", id: 29 }],
    price: 32,
    rating: 4.2,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1922-02-02"),
  },
  {
    id: 29,
    title: "The Trial",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780805209990-L.jpg",
    authors: [{ firstName: "Franz", lastName: "Kafka", id: 30 }],
    price: 23,
    rating: 4.5,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1914-1915"),
  },
  {
    id: 30,
    title: "1984",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    authors: [{ firstName: "George", lastName: "Orwell", id: 31 }],
    price: 18,
    rating: 4.7,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1949-06-08"),
  },
  {
    id: 31,
    title: "The Great Gatsby",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    authors: [{ firstName: "F. Scott", lastName: "Fitzgerald", id: 32 }],
    price: 22,
    rating: 4.4,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1925-04-10"),
  },
  {
    id: 32,
    title: "Brave New World",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
    authors: [{ firstName: "Aldous", lastName: "Huxley", id: 33 }],
    price: 560,
    rating: 4.3,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1932-01-01"),
  },
  {
    id: 33,
    title: "The Chronicles of Narnia",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780064471190-L.jpg",
    authors: [{ firstName: "C.S.", lastName: "Lewis", id: 34 }],
    price: 30,
    rating: 4.8,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1950-10-16"),
  },
  {
    id: 34,
    title: "The Jungle Book",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141330979-L.jpg",
    authors: [{ firstName: "Rudyard", lastName: "Kipling", id: 35 }],
    price: 180,
    rating: 4.5,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1894-01-01"),
  },
  {
    id: 35,
    title: "The War of the Worlds",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780451531588-L.jpg",
    authors: [{ firstName: "H.G.", lastName: "Wells", id: 36 }],
    price: 200,
    rating: 4.4,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1898-01-01"),
  },
  {
    id: 36,
    title: "The Secret Garden",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780064401882-L.jpg",
    authors: [{ firstName: "Frances", lastName: "Hodgson Burnett", id: 37 }],
    price: 190,
    rating: 4.6,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1911-08-01"),
  },
  {
    id: 37,
    title: "Dr. Jekyll and Mr. Hyde",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141439730-L.jpg",
    authors: [{ firstName: "Robert Louis", lastName: "Stevenson", id: 38 }],
    price: 15,
    rating: 4.3,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1886-01-01"),
  },
  {
    id: 38,
    title: "The Call of the Wild",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780060937157-L.jpg",
    authors: [{ firstName: "Jack", lastName: "London", id: 39 }],
    price: 200,
    rating: 4.6,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1903-08-22"),
  },
  {
    id: 39,
    title: "The Scarlet Letter",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780142437261-L.jpg",
    authors: [{ firstName: "Nathaniel", lastName: "Hawthorne", id: 40 }],
    price: 17,
    rating: 4.2,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1850-03-16"),
  },
  {
    id: 40,
    title: "Frankenstein",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141439471-L.jpg",
    authors: [{ firstName: "Mary", lastName: "Shelley", id: 15 }],
    price: 180,
    rating: 4.7,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1818-01-01"),
  },
  {
    id: 41,
    title: "1984",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    authors: [{ firstName: "George", lastName: "Orwell", id: 41 }],
    price: 215,
    rating: 4.7,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1949-06-08"),
  },
  {
    id: 42,
    title: "Fahrenheit 451",
    coverUri: "https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg",
    authors: [{ firstName: "Ray", lastName: "Bradbury", id: 42 }],
    price: 22,
    rating: 4.6,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1953-10-19"),
  },
  {
    id: 43,
    title: "The Catcher in the Rye",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
    authors: [{ firstName: "J.D.", lastName: "Salinger", id: 43 }],
    price: 198,
    rating: 4.2,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1951-07-16"),
  },
  {
    id: 44,
    title: "Moby-Dick",
    coverUri: "https://covers.openlibrary.org/b/isbn/9781853260087-L.jpg",
    authors: [{ firstName: "Herman", lastName: "Melville", id: 44 }],
    price: 25,
    rating: 4.5,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1851-11-14"),
  },
  {
    id: 45,
    title: "The Hobbit",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780345339683-L.jpg",
    authors: [{ firstName: "J.R.R.", lastName: "Tolkien", id: 45 }],
    price: 186,
    rating: 4.8,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1937-09-21"),
  },
  {
    id: 46,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780547928210-L.jpg",
    authors: [{ firstName: "J.R.R.", lastName: "Tolkien", id: 45 }],
    price: 30,
    rating: 4.9,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1954-07-29"),
  },
  {
    id: 47,
    title: "The Lord of the Rings: The Two Towers",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780547928203-L.jpg",
    authors: [{ firstName: "J.R.R.", lastName: "Tolkien", id: 45 }],
    price: 30,
    rating: 4.8,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1954-11-11"),
  },
  {
    id: 48,
    title: "The Lord of the Rings: The Return of the King",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780547928197-L.jpg",
    authors: [{ firstName: "J.R.R.", lastName: "Tolkien", id: 45 }],
    price: 324,
    rating: 4.9,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1955-10-20"),
  },
  {
    id: 49,
    title: "The Picture of Dorian Gray",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141439570-L.jpg",
    authors: [{ firstName: "Oscar", lastName: "Wilde", id: 46 }],
    price: 19,
    rating: 4.3,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1890-06-01"),
  },
  {
    id: 50,
    title: "The Stranger",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780679720201-L.jpg",
    authors: [{ firstName: "Albert", lastName: "Camus", id: 47 }],
    price: 211,
    rating: 4.6,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1942-06-01"),
  },
  {
    id: 51,
    title: "The Sun Also Rises",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780743297336-L.jpg",
    authors: [{ firstName: "Ernest", lastName: "Hemingway", id: 48 }],
    price: 20,
    rating: 4.5,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1926-10-22"),
  },
  {
    id: 52,
    title: "The Old Man and the Sea",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780684801223-L.jpg",
    authors: [{ firstName: "Ernest", lastName: "Hemingway", id: 48 }],
    price: 188,
    rating: 4.7,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1952-09-01"),
  },
  {
    id: 53,
    title: "Slaughterhouse-Five",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780385333849-L.jpg",
    authors: [{ firstName: "Kurt", lastName: "Vonnegut", id: 49 }],
    price: 23,
    rating: 4.4,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1969-03-31"),
  },
  {
    id: 54,
    title: "The Bell Jar",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780060837020-L.jpg",
    authors: [{ firstName: "Sylvia", lastName: "Plath", id: 50 }],
    price: 18,
    rating: 4.6,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1963-01-01"),
  },
  {
    id: 55,
    title: "The Road",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780307387899-L.jpg",
    authors: [{ firstName: "Cormac", lastName: "McCarthy", id: 51 }],
    price: 246,
    rating: 4.8,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("2006-09-26"),
  },
  {
    id: 56,
    title: "Atonement",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780307263438-L.jpg",
    authors: [{ firstName: "Ian", lastName: "McEwan", id: 52 }],
    price: 25,
    rating: 4.7,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("2001-09-01"),
  },
  {
    id: 57,
    title: "The Kite Runner",
    coverUri: "https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg",
    authors: [{ firstName: "Khaled", lastName: "Hosseini", id: 53 }],
    price: 23,
    rating: 4.9,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("2003-05-29"),
  },
  {
    id: 58,
    title: "The Alchemist",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
    authors: [{ firstName: "Paulo", lastName: "Coelho", id: 54 }],
    price: 0,
    rating: 4.7,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1988-05-01"),
  },
  {
    id: 59,
    title: "The Handmaid's Tale",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg",
    authors: [{ firstName: "Margaret", lastName: "Atwood", id: 55 }],
    price: 282,
    rating: 4.6,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1985-08-01"),
  },
  {
    id: 60,
    title: "The Hunger Games",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780439023528-L.jpg",
    authors: [{ firstName: "Suzanne", lastName: "Collins", id: 56 }],
    price: 10,
    rating: 4.5,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("2008-09-14"),
  },
  {
    id: 61,
    title: "Brave New World",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
    authors: [{ firstName: "Aldous", lastName: "Huxley", id: 57 }],
    price: 22,
    rating: 4.4,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1932-08-01"),
  },
  {
    id: 62,
    title: "The Great Gatsby",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    authors: [{ firstName: "F. Scott", lastName: "Fitzgerald", id: 58 }],
    price: 185,
    rating: 4.3,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1925-04-10"),
  },
  {
    id: 63,
    title: "Animal Farm",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780451526342-L.jpg",
    authors: [{ firstName: "George", lastName: "Orwell", id: 41 }],
    price: 516,
    rating: 4.7,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1945-08-17"),
  },
  {
    id: 64,
    title: "To Kill a Mockingbird",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780060935467-L.jpg",
    authors: [{ firstName: "Harper", lastName: "Lee", id: 59 }],
    price: 19,
    rating: 4.8,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1960-07-11"),
  },
  {
    id: 65,
    title: "Pride and Prejudice",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    authors: [{ firstName: "Jane", lastName: "Austen", id: 60 }],
    price: 105,
    rating: 4.9,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1813-01-28"),
  },
  {
    id: 66,
    title: "Wuthering Heights",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg",
    authors: [{ firstName: "Emily", lastName: "Brontë", id: 61 }],
    price: 0,
    rating: 4.4,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1847-12-01"),
  },
  {
    id: 67,
    title: "Jane Eyre",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg",
    authors: [{ firstName: "Charlotte", lastName: "Brontë", id: 62 }],
    price: 179,
    rating: 4.6,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1847-10-16"),
  },
  {
    id: 68,
    title: "Frankenstein",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780486282114-L.jpg",
    authors: [{ firstName: "Mary", lastName: "Shelley", id: 63 }],
    price: 0,
    rating: 4.5,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1818-01-01"),
  },
  {
    id: 69,
    title: "Dracula",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780141439847-L.jpg",
    authors: [{ firstName: "Bram", lastName: "Stoker", id: 64 }],
    price: 65,
    rating: 4.7,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1897-05-26"),
  },
  {
    id: 70,
    title: "The Shining",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780307743657-L.jpg",
    authors: [{ firstName: "Stephen", lastName: "King", id: 65 }],
    price: 78,
    rating: 4.8,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1977-01-28"),
  },
  {
    id: 71,
    title: "It",
    coverUri: "https://covers.openlibrary.org/b/isbn/9781501142970-L.jpg",
    authors: [{ firstName: "Stephen", lastName: "King", id: 65 }],
    price: 0,
    rating: 4.5,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1986-09-15"),
  },
  {
    id: 72,
    title: "The Stand",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780385121670-L.jpg",
    authors: [{ firstName: "Stephen", lastName: "King", id: 65 }],
    price: 711,
    rating: 4.6,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("1978-09-01"),
  },
  {
    id: 73,
    title: "The Outsiders",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780142407332-L.jpg",
    authors: [{ firstName: "S.E.", lastName: "Hinton", id: 66 }],
    price: 456,
    rating: 4.3,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("1967-04-24"),
  },
  {
    id: 74,
    title: "The Girl on the Train",
    coverUri: "https://covers.openlibrary.org/b/isbn/9781594633669-L.jpg",
    authors: [{ firstName: "Paula", lastName: "Hawkins", id: 67 }],
    price: 23,
    rating: 4.0,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("2015-01-13"),
  },
  {
    id: 75,
    title: "Gone Girl",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg",
    authors: [{ firstName: "Gillian", lastName: "Flynn", id: 68 }],
    price: 111,
    rating: 4.2,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("2012-06-05"),
  },
  {
    id: 76,
    title: "Big Little Lies",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780399587201-L.jpg",
    authors: [{ firstName: "Liane", lastName: "Moriarty", id: 69 }],
    price: 22.56,
    rating: 4.3,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("2014-07-29"),
  },
  {
    id: 77,
    title: "The Silent Patient",
    coverUri: "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg",
    authors: [{ firstName: "Alex", lastName: "Michaelides", id: 70 }],
    price: 528,
    rating: 4.5,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("2019-02-05"),
  },
  {
    id: 78,
    title: "The Couple Next Door",
    coverUri: "https://covers.openlibrary.org/b/isbn/9781101967603-L.jpg",
    authors: [{ firstName: "Shari", lastName: "Lapena", id: 71 }],
    price: 21,
    rating: 4.1,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("2016-08-23"),
  },
  {
    id: 79,
    title: "Where the Crawdads Sing",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780735219090-L.jpg",
    authors: [{ firstName: "Delia", lastName: "Owens", id: 72 }],
    price: 742,
    rating: 4.7,
    isAudio: false,
    isInfinity: true,
    createdAt: new Date("2018-08-14"),
  },
  {
    id: 80,
    title: "The Night Circus",
    coverUri: "https://covers.openlibrary.org/b/isbn/9780307744432-L.jpg",
    authors: [{ firstName: "Erin", lastName: "Morgenstern", id: 73 }],
    price: 723,
    rating: 4.6,
    isAudio: true,
    isInfinity: false,
    createdAt: new Date("2011-09-13"),
  },
];

export default books;
